//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_DatabaseApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Atmosfera
    {
        public int AtmosferaID { get; set; }
        public int PlanetaID { get; set; }
        public Nullable<short> Grubosc_atmosfery_km { get; set; }
        public string Temperatura_atmosfery_stopnieC { get; set; }
        public string Sklad_atmosfery { get; set; }
    
        public virtual Planety Planety { get; set; }
    }
}
