//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_DatabaseApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Atmosfera_gwiazd
    {
        public int AtmosferaID { get; set; }
        public int GwiazdaID { get; set; }
        public string Temperatura_atmosfery_stopnieC_gwiazdy { get; set; }
        public string Sklad_atmosfery_gwiazdy { get; set; }
    
        public virtual Gwiazdy Gwiazdy { get; set; }
    }
}
