//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_DatabaseApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Gwiazdy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gwiazdy()
        {
            this.Atmosfera_gwiazd = new ObservableCollection<Atmosfera_gwiazd>();
            this.Planety = new ObservableCollection<Planety>();
        }
    
        public int GwiazdaID { get; set; }
        public string Nazwa_gwiazdy { get; set; }
        public string Rodzaj_gwiazdy { get; set; }
        public Nullable<decimal> Oddalenie_od_ukladu_slonecznego_ly { get; set; }
        public Nullable<short> Liczba_obiegajacych_planet { get; set; }
        public Nullable<long> Srednica_gwiazdy_km { get; set; }
        public string Masa_gwiazdy_kg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Atmosfera_gwiazd> Atmosfera_gwiazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Planety> Planety { get; set; }
    }
}
