//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_DatabaseApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Planety_archiwumEntities : DbContext
    {
        public Planety_archiwumEntities()
            : base("name=Planety_archiwumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atmosfera> Atmosfera { get; set; }
        public virtual DbSet<Atmosfera_gwiazd> Atmosfera_gwiazd { get; set; }
        public virtual DbSet<Gwiazdy> Gwiazdy { get; set; }
        public virtual DbSet<Naturalne_satelity> Naturalne_satelity { get; set; }
        public virtual DbSet<Planety> Planety { get; set; }
    }
}
