//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_DatabaseApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Planety
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planety()
        {
            this.Atmosfera = new ObservableCollection<Atmosfera>();
            this.Naturalne_satelity = new ObservableCollection<Naturalne_satelity>();
        }
    
        public int PlanetaID { get; set; }
        public Nullable<int> GwiazdaID { get; set; }
        public string Nazwa { get; set; }
        public string Rodzaj_planety { get; set; }
        public Nullable<long> Srednia_odleglosc_od_gwiazdy_km { get; set; }
        public Nullable<decimal> Rok_gwiazdowy_dni { get; set; }
        public Nullable<short> Liczba_naturalnych_satelit { get; set; }
        public string Powierzchnia_km2 { get; set; }
        public string Masa_kg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Atmosfera> Atmosfera { get; set; }
        public virtual Gwiazdy Gwiazdy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Naturalne_satelity> Naturalne_satelity { get; set; }
    }
}
